<?php
$data = array (
  0 => 
  array (
    'cat_id' => '131',
    'cat_name' => '进口奶粉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '10',
    'goods_num' => '172',
  ),
  1 => 
  array (
    'cat_id' => '138',
    'cat_name' => '宝宝辅食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '9',
    'goods_num' => '122',
  ),
  2 => 
  array (
    'cat_id' => '266',
    'cat_name' => '宝宝营养品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => '23',
  ),
  3 => 
  array (
    'cat_id' => '141',
    'cat_name' => '宝宝日用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '6',
    'goods_num' => '52',
  ),
  4 => 
  array (
    'cat_id' => '268',
    'cat_name' => '宝宝喂养用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '6',
    'goods_num' => '6',
  ),
  5 => 
  array (
    'cat_id' => '145',
    'cat_name' => '零食',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '151',
    'cat_name' => '化妆品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '6',
    'goods_num' => '1',
  ),
  7 => 
  array (
    'cat_id' => '343',
    'cat_name' => '1岁以上',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '244',
    'cat_name' => '优惠套装',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '4',
    'goods_num' => '28',
  ),
  9 => 
  array (
    'cat_id' => '196',
    'cat_name' => '国别',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '197',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '200',
    'cat_name' => '阶段',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '132',
    'cat_name' => '0-6',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  13 => 
  array (
    'cat_id' => '133',
    'cat_name' => '6-10',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '134',
    'cat_name' => '10-12',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '135',
    'cat_name' => '1岁上',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '136',
    'cat_name' => '2岁上',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => '8',
  ),
  17 => 
  array (
    'cat_id' => '137',
    'cat_name' => '3岁上',
    'measure_unit' => '',
    'parent_id' => '131',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  18 => 
  array (
    'cat_id' => '201',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '39',
    'has_children' => '10',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '157',
    'cat_name' => '热门品牌',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  20 => 
  array (
    'cat_id' => '333',
    'cat_name' => '肉泥/果泥',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  21 => 
  array (
    'cat_id' => '334',
    'cat_name' => '泡芙',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  22 => 
  array (
    'cat_id' => '331',
    'cat_name' => '米粉',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  23 => 
  array (
    'cat_id' => '335',
    'cat_name' => '小溶豆',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  24 => 
  array (
    'cat_id' => '332',
    'cat_name' => '磨牙/饼干',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  25 => 
  array (
    'cat_id' => '202',
    'cat_name' => '国别',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '99',
    'has_children' => '7',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '297',
    'cat_name' => '年龄',
    'measure_unit' => '',
    'parent_id' => '138',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '101',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '203',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '16',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '204',
    'cat_name' => '国别',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '248',
    'cat_name' => '热门品牌',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  30 => 
  array (
    'cat_id' => '142',
    'cat_name' => '纸尿裤',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  31 => 
  array (
    'cat_id' => '144',
    'cat_name' => '洗护用品',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '158',
    'cat_name' => '日常用品',
    'measure_unit' => '',
    'parent_id' => '141',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  33 => 
  array (
    'cat_id' => '146',
    'cat_name' => '热门品牌',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '148',
    'cat_name' => '组合套装',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '149',
    'cat_name' => '办公冲调品',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '150',
    'cat_name' => '休闲食品',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '211',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '145',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '152',
    'cat_name' => '热门品牌',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '218',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '153',
    'cat_name' => '美容护肤',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '154',
    'cat_name' => '靓丽彩妆',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '155',
    'cat_name' => '香水精油',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '156',
    'cat_name' => '美体护发',
    'measure_unit' => '',
    'parent_id' => '151',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '55',
    'has_children' => '1',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '221',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '153',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '21',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '222',
    'cat_name' => '唇妆',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '223',
    'cat_name' => '面妆',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '239',
    'cat_name' => '眼妆',
    'measure_unit' => '',
    'parent_id' => '154',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '254',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '155',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '235',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '156',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '164',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '161',
    'cat_name' => '英国',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '165',
    'cat_name' => '香港',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '162',
    'cat_name' => '新西兰',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '159',
    'cat_name' => '荷兰',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '163',
    'cat_name' => '瑞典',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '160',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '205',
    'cat_name' => '澳洲',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '101',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '338',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '196',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '102',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '198',
    'cat_name' => '配方奶粉',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '199',
    'cat_name' => '过敏体质奶粉',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '336',
    'cat_name' => '孕妇奶粉',
    'measure_unit' => '',
    'parent_id' => '197',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '347',
    'cat_name' => '0-6个月',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '151',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '348',
    'cat_name' => '7-9个月',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '152',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '349',
    'cat_name' => '7-12个月',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '153',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '350',
    'cat_name' => '1岁以上',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '154',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '351',
    'cat_name' => '2岁以上',
    'measure_unit' => '',
    'parent_id' => '200',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '155',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '173',
    'cat_name' => '米粉',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '48',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '326',
    'cat_name' => '糖果',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  69 => 
  array (
    'cat_id' => '324',
    'cat_name' => '面条',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '327',
    'cat_name' => '果汁',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '325',
    'cat_name' => '肉松',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '322',
    'cat_name' => '小溶豆',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '323',
    'cat_name' => '麦片',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '174',
    'cat_name' => '肉泥/果泥',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '101',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '175',
    'cat_name' => '泡芙',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '103',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  76 => 
  array (
    'cat_id' => '206',
    'cat_name' => '磨牙/饼干',
    'measure_unit' => '',
    'parent_id' => '201',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '104',
    'has_children' => '0',
    'goods_num' => '4',
  ),
  77 => 
  array (
    'cat_id' => '184',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '200',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '185',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '201',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '186',
    'cat_name' => '中国台湾',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '202',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '187',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '203',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '189',
    'cat_name' => '澳洲',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '207',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '190',
    'cat_name' => '荷兰',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '208',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '207',
    'cat_name' => '意大利',
    'measure_unit' => '',
    'parent_id' => '202',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '209',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '306',
    'cat_name' => '湿巾',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '310',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '307',
    'cat_name' => '通鼻精油',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '208',
    'cat_name' => '纸尿裤',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  88 => 
  array (
    'cat_id' => '311',
    'cat_name' => '消毒杀菌',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '308',
    'cat_name' => '指甲钳',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  90 => 
  array (
    'cat_id' => '305',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '304',
    'cat_name' => '退热贴',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  92 => 
  array (
    'cat_id' => '243',
    'cat_name' => '驱蚊止痒',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '309',
    'cat_name' => '防晒',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '240',
    'cat_name' => '牙膏',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '179',
    'cat_name' => '牙刷',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '241',
    'cat_name' => '爽身粉',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '102',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '181',
    'cat_name' => '保湿护肤',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '102',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  98 => 
  array (
    'cat_id' => '183',
    'cat_name' => '沐浴/洗发',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '104',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '210',
    'cat_name' => '其它',
    'measure_unit' => '',
    'parent_id' => '203',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '105',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '192',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '202',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '193',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '203',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '194',
    'cat_name' => '英国',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '205',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '191',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '204',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '207',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '216',
    'cat_name' => '坚果/果仁',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '213',
    'cat_name' => '糖果/巧克力',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '247',
    'cat_name' => '干果/蜜饯',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '214',
    'cat_name' => '冲泡饮品',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '215',
    'cat_name' => '蜂蜜',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '212',
    'cat_name' => '饼干/糕点',
    'measure_unit' => '',
    'parent_id' => '211',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '260',
    'cat_name' => '男士护肤套装',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '237',
    'cat_name' => '女士护肤套装',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '257',
    'cat_name' => '男士化妆水/爽肤水',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '233',
    'cat_name' => '晒后修复',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '230',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '251',
    'cat_name' => '男士洁面',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '227',
    'cat_name' => '女士化妆水/爽肤水',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '265',
    'cat_name' => '手足护理',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '262',
    'cat_name' => '男士眼部护理',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '238',
    'cat_name' => '女士眼部护理',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '261',
    'cat_name' => '男士精华露',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '236',
    'cat_name' => '身体乳、霜',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '231',
    'cat_name' => '女士面霜/润肤乳',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '228',
    'cat_name' => '女士洁面',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '225',
    'cat_name' => '唇部护理',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '259',
    'cat_name' => '男士面霜/润肤乳',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '253',
    'cat_name' => '护理油',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '229',
    'cat_name' => '女士精华露',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '250',
    'cat_name' => '磨砂膏',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '226',
    'cat_name' => '女士防晒霜',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '264',
    'cat_name' => '女士卸妆',
    'measure_unit' => '',
    'parent_id' => '221',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '252',
    'cat_name' => '护发',
    'measure_unit' => '',
    'parent_id' => '235',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '249',
    'cat_name' => '美体塑身',
    'measure_unit' => '',
    'parent_id' => '235',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '232',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '235',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '339',
    'cat_name' => '买九送二',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '340',
    'cat_name' => '买六送一',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '341',
    'cat_name' => '四罐套装',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '352',
    'cat_name' => '两罐套装',
    'measure_unit' => '',
    'parent_id' => '244',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '255',
    'cat_name' => '女士香水',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '263',
    'cat_name' => '中性香水',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '256',
    'cat_name' => '男士香水',
    'measure_unit' => '',
    'parent_id' => '254',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '277',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '266',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '8',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '273',
    'cat_name' => '国别',
    'measure_unit' => '',
    'parent_id' => '266',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '283',
    'cat_name' => '年龄',
    'measure_unit' => '',
    'parent_id' => '266',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '272',
    'cat_name' => '热门品牌',
    'measure_unit' => '',
    'parent_id' => '266',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '49',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '293',
    'cat_name' => '类目',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '9',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '291',
    'cat_name' => '热门品牌',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '292',
    'cat_name' => '国别',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '330',
    'cat_name' => '叉/勺/碗',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  149 => 
  array (
    'cat_id' => '328',
    'cat_name' => '奶瓶',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  150 => 
  array (
    'cat_id' => '329',
    'cat_name' => '奶嘴',
    'measure_unit' => '',
    'parent_id' => '268',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '6',
  ),
  151 => 
  array (
    'cat_id' => '274',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  152 => 
  array (
    'cat_id' => '275',
    'cat_name' => '意大利',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '337',
    'cat_name' => '英国',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '276',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '273',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '289',
    'cat_name' => '调节肠胃',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '278',
    'cat_name' => '益生菌',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '290',
    'cat_name' => '婴儿补锌',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '279',
    'cat_name' => '维生素',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '281',
    'cat_name' => '鱼肝油',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '288',
    'cat_name' => '清火开胃',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '282',
    'cat_name' => 'DHA',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '280',
    'cat_name' => '提高免疫',
    'measure_unit' => '',
    'parent_id' => '277',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '284',
    'cat_name' => '0-6个月',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '285',
    'cat_name' => '6-12个月',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '286',
    'cat_name' => '1岁以上',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '287',
    'cat_name' => '2岁以上',
    'measure_unit' => '',
    'parent_id' => '283',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '296',
    'cat_name' => '日本',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '303',
    'cat_name' => '瑞典',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '294',
    'cat_name' => '美国',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '295',
    'cat_name' => '德国',
    'measure_unit' => '',
    'parent_id' => '292',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '316',
    'cat_name' => '儿童围兜',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '313',
    'cat_name' => '叉/勺/碗',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  173 => 
  array (
    'cat_id' => '271',
    'cat_name' => '奶嘴',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '24',
  ),
  174 => 
  array (
    'cat_id' => '317',
    'cat_name' => '宝宝食物存储',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '314',
    'cat_name' => '餐垫',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  176 => 
  array (
    'cat_id' => '321',
    'cat_name' => '奶瓶辅助工具',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '5',
  ),
  177 => 
  array (
    'cat_id' => '315',
    'cat_name' => '辅食料工具',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '2',
  ),
  178 => 
  array (
    'cat_id' => '312',
    'cat_name' => '牙胶',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '270',
    'cat_name' => '奶瓶',
    'measure_unit' => '',
    'parent_id' => '293',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '27',
  ),
  180 => 
  array (
    'cat_id' => '298',
    'cat_name' => '4个月以上',
    'measure_unit' => '',
    'parent_id' => '297',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '299',
    'cat_name' => '6个月以上',
    'measure_unit' => '',
    'parent_id' => '297',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '51',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '302',
    'cat_name' => '8个月以上',
    'measure_unit' => '',
    'parent_id' => '297',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '52',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  183 => 
  array (
    'cat_id' => '300',
    'cat_name' => '1岁以上',
    'measure_unit' => '',
    'parent_id' => '297',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '53',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  184 => 
  array (
    'cat_id' => '301',
    'cat_name' => '2岁以上',
    'measure_unit' => '',
    'parent_id' => '297',
    'is_show' => '0',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '54',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>