<?php
$data = array (
  360 => 
  array (
    'cat_id' => '360',
    'cat_name' => '奶粉',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
    'level' => 0,
    'id' => '360',
    'name' => '奶粉',
  ),
  364 => 
  array (
    'cat_id' => '364',
    'cat_name' => '3',
    'measure_unit' => '',
    'parent_id' => '360',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '364',
    'name' => '3',
  ),
  365 => 
  array (
    'cat_id' => '365',
    'cat_name' => '4',
    'measure_unit' => '',
    'parent_id' => '360',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '365',
    'name' => '4',
  ),
  362 => 
  array (
    'cat_id' => '362',
    'cat_name' => '1',
    'measure_unit' => '',
    'parent_id' => '360',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '362',
    'name' => '1',
  ),
  375 => 
  array (
    'cat_id' => '375',
    'cat_name' => '6',
    'measure_unit' => '',
    'parent_id' => '360',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '375',
    'name' => '6',
  ),
  366 => 
  array (
    'cat_id' => '366',
    'cat_name' => '5',
    'measure_unit' => '',
    'parent_id' => '360',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '366',
    'name' => '5',
  ),
  363 => 
  array (
    'cat_id' => '363',
    'cat_name' => '2',
    'measure_unit' => '',
    'parent_id' => '360',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '363',
    'name' => '2',
  ),
  359 => 
  array (
    'cat_id' => '359',
    'cat_name' => '面包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '359',
    'name' => '面包',
  ),
  370 => 
  array (
    'cat_id' => '370',
    'cat_name' => '北包',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '370',
    'name' => '北包',
  ),
  367 => 
  array (
    'cat_id' => '367',
    'cat_name' => '中包',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '367',
    'name' => '中包',
  ),
  371 => 
  array (
    'cat_id' => '371',
    'cat_name' => '东包',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '371',
    'name' => '东包',
  ),
  368 => 
  array (
    'cat_id' => '368',
    'cat_name' => '西包',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '368',
    'name' => '西包',
  ),
  369 => 
  array (
    'cat_id' => '369',
    'cat_name' => '南包',
    'measure_unit' => '',
    'parent_id' => '359',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '369',
    'name' => '南包',
  ),
  353 => 
  array (
    'cat_id' => '353',
    'cat_name' => '蛋糕',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '353',
    'name' => '蛋糕',
  ),
  355 => 
  array (
    'cat_id' => '355',
    'cat_name' => '星座',
    'measure_unit' => '',
    'parent_id' => '353',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '355',
    'name' => '星座',
  ),
  354 => 
  array (
    'cat_id' => '354',
    'cat_name' => '水果',
    'measure_unit' => '',
    'parent_id' => '353',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '354',
    'name' => '水果',
  ),
  358 => 
  array (
    'cat_id' => '358',
    'cat_name' => '核桃',
    'measure_unit' => '',
    'parent_id' => '353',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '358',
    'name' => '核桃',
  ),
  356 => 
  array (
    'cat_id' => '356',
    'cat_name' => '巧克力',
    'measure_unit' => '',
    'parent_id' => '353',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '356',
    'name' => '巧克力',
  ),
  357 => 
  array (
    'cat_id' => '357',
    'cat_name' => '奶油',
    'measure_unit' => '',
    'parent_id' => '353',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '357',
    'name' => '奶油',
  ),
  361 => 
  array (
    'cat_id' => '361',
    'cat_name' => '其他',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '100',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '361',
    'name' => '其他',
  ),
  374 => 
  array (
    'cat_id' => '374',
    'cat_name' => '3',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '374',
    'name' => '3',
  ),
  372 => 
  array (
    'cat_id' => '372',
    'cat_name' => '1',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '372',
    'name' => '1',
  ),
  373 => 
  array (
    'cat_id' => '373',
    'cat_name' => '2',
    'measure_unit' => '',
    'parent_id' => '361',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
    'level' => 1,
    'id' => '373',
    'name' => '2',
  ),
);
?>